{% set name = "minepy" %}
{% set version = "1.2.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f488a1bc8de9e4c1043e3fe090682378266eb445d632a68f30b815268c31b918

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >=1.3.0
    - pip
    - python
    - setuptools <58
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - minepy

about:
  home: http://minepy.readthedocs.io
  license: GPL-3.0-only
  license_family: LGPL
  license_file: gpl-3.0.txt
  summary: minepy - Maximal Information-based Nonparametric Exploration
  doc_url: http://minepy.readthedocs.io
  dev_url: https://github.com/minepy/minepy

extra:
  recipe-maintainers:
    - philip-khor
